require 'rake'
require 'fileutils'

# Build the extension with Rake.
# Most of this is duplicated functionality except for the wrapper task.

SWIG = "swig"

extname = "firstgem"
extlib = "#{extname}.#{RbConfig::CONFIG["DLEXT"]}"
install_dir = "../../lib"
installed_lib = File.join(install_dir, extlib)

file 'Makefile' do
  system 'ruby extconf.rb'
end

task :runmake => ['Makefile'] do
  system 'make'
end

task extlib => :runmake

desc "Compile extension and move to the gem lib folder"
task :compile => extlib do
  File.delete installed_lib if File.exists?(installed_lib)
  FileUtils.move(extlib, install_dir)
end

desc "Remove generated extension files."
task :clean do
  FileUtils.rm_f([installed_lib, 'Makefile', Dir.glob('*.o')])
end

desc "Run swig wrapper generator on all .i interface files."
task :wrapper do
  system "#{SWIG} -c++ -ruby *.i"
  
  # Replace STR2CSTR with StringValuePtr for Ruby 1.9
  if RUBY_VERSION =~ /^1.9/
    if RUBY_PLATFORM =~ /darwin/ 
      system "sed -i '' -e 's/STR2CSTR/StringValuePtr/' *.cxx"
    else
      system "sed -i -e 's/STR2CSTR/StringValuePtr/' *.cxx"
    end
  end
  
end

task :default => :compile

